(Invoke-WebRequest -Uri "https://www.dealabs.com/").BaseResponse
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Content
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Encoding
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Headers
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Images
(Invoke-WebRequest -Uri "https://www.dealabs.com/").InputFields
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Links
(Invoke-WebRequest -Uri "https://www.dealabs.com/").RawContent
(Invoke-WebRequest -Uri "https://www.dealabs.com/").RawContentLength
(Invoke-WebRequest -Uri "https://www.dealabs.com/").RawContentStream
(Invoke-WebRequest -Uri "https://www.dealabs.com/").RelationLink
(Invoke-WebRequest -Uri "https://www.dealabs.com/").StatusCode
(Invoke-WebRequest -Uri "https://www.dealabs.com/").StatusDescription
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Forms
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Cookies
(Invoke-WebRequest -Uri "https://www.dealabs.com/").ParsedHtml
(Invoke-WebRequest -Uri "https://www.dealabs.com/").Links.Href
(Invoke-WebRequest -Uri "https://thehackernews.com/").Links.OuterText